Make pull request branch
CIASIE-2018/TIL pull request #3
Opened 2018-09-17 12:17 UTC by JesterHeads

Comment faire une PullRequest et à quoi ça nous sert dans le cadre du cours

2018-09-17 12:18 UTC, AnthonyZink approved these changes

2018-09-18 10:49 UTC, Briand-Lucas approved these changes

2018-09-19 11:06 UTC, floo51 requested changes

2018-09-19 11:06 UTC, floo51 commented on Programmation Web Serveur/.idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Ce fichier ne doit pas être commit

2018-09-19 11:06 UTC, floo51 commented on Programmation Web Serveur/CreerUnePullRequest.md
> +Nous avons vu comment faire une pull requesten bonne et dû forme, à quoi cela nous servira dans le cadre de nos cours et pour plus tard.<br>
Il manque un espace `pull request_en bonne et due forme`

2018-09-19 11:06 UTC, floo51 commented on Programmation Web Serveur/CreerUnePullRequest.md
> +Nous avons vu comment faire une pull requesten bonne et dû forme, à quoi cela nous servira dans le cadre de nos cours et pour plus tard.<br>
Due prend un E

2018-09-19 11:06 UTC, floo51 commented on Programmation Web Serveur/CreerUnePullRequest.md
> +Nous avons vu comment faire une pull requesten bonne et dû forme, à quoi cela nous servira dans le cadre de nos cours et pour plus tard.<br>
Les saut de lignes en markdown ne sont pas avec des `<br/>` mais de simple sauts de ligne dans le fichier.

2018-09-22 09:51 UTC, Briand-Lucas approved these changes

2018-09-22 09:55 UTC, merged